site:
  title: FIXME Course Title
  start_page: Deploying MicroShift on RHEL Image Mode

content:
  sources:
  - url: ./

asciidoc:
  attributes:
    page-pagination: true

ui:
  bundle:
    url: ./ui-bundle/ui-bundle.zip
  supplemental_files: ./supplemental-ui
