:time_estimate: 5
:compose-commit-uuid-aaaaaaaaaaaaaa: be27c45f-e1ea-42eb-94b3-a0789243bea4
:compose-installer-uuid-aaaaaaaaaaa: 170edc4e-9384-4e86-b616-7c09eaa718e4

= Lab: Create Bootc Container Images with MicroShift

_Estimated reading time: *{time_estimate} minutes*._

Objective::

Provision a RHEL image mode system with MicroShift, fully disconnected, from an installation ISO.

WARNING: Work In Progress

IMPORTANT: Rewrite this as needed for image mode, may extract pieces to partials if they fit both RPM-OSTree and bootc

== Before you Begin

You need a few machines to perform the hands-on activities in this course. 

* A _development machine_ with RHEL and unrestricted `sudo`, where you will create KVM VMs using Libvirt, build bootc container iamges, run bootc image builder, and also run the OpenShift client to access your MicroShift instances.

* A _package server machine_ already configured to serve DNF repositories for RHEL, Fast Datapath for RHEL, and Red Hat OpenShift Container Platform.

* A _web server machine_ with RHEL and unrestricted `sudo`, to miscelaneous files for your RHEL and MicroShift VMs.

* A _mirror registry machine_ with RHEL and unrestricted `sudo`, already populated with the container images required by MicroShift and sample applications.

Make sure that your _package server machine_ and _mirror registry machine_ are properly configured and verified by following the instructions from a xref:ch1-microshift:s3-air-gapped-lab.adoc[previous lab] of this course.

These instructions were tested on RHEL 9.5 but should work with minimal or no change on newer and older RHEL 9.x releases.

If you are using the course environment, you will log in to the `workstation` VM as the user `student` with password `student`. The `workstation` VM is your _development machine_. You will start SSH sessions from the `workstation` VM to the `servera` VM, which is your _web server machine_ and also your _mirror registry machine_, using the same user.

You will also create a local KVM virtual machine on your _development machine_, and we refer to that VM as your _edge machine_.

IMPORTANT: Be sure you execute each step on the correct machine. If a step is not explicit about the machine it should be performed, it is using the same machine as its previous step.

== Instructions

1. On your _development machine_, verify that you have all prerequisites from previous labs.

.. Check that you can access your _web server machine_.
+
[source,subs="verbatim,quotes"]
--
$ *curl http://servera.lab.example.com*
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
        <head>
                <title>Test Page for the HTTP Server on Red Hat Enterprise Linux</title>
...
--

.. Check that your unprivileged user has access to Libvirt session VMs.
+
[source,subs="verbatim,quotes"]
--
$ *virsh uri*
qemu:///session
$ *virsh nodeinfo*
CPU model:           x86_64
...
--

.. Check that you have a valid pull secret for your your _mirror registry machine_ and that you can access it with TLS validation enabled. [ Review this output because of bootc containers ]
+
[source,subs="verbatim,quotes"]
--
$ *podman search --authfile mirror-pull-secret servera.lab.example.com:8443/*
NAME                                                                 DESCRIPTION
servera.lab.example.com:8443/lvms4/lvms-rhel9-operator               
servera.lab.example.com:8443/openshift-release-dev/ocp-v4.0-art-dev  
servera.lab.example.com:8443/rhel9/mysql-80                          
servera.lab.example.com:8443/flozanorht/php-ubi                      
servera.lab.example.com:8443/ubi9/ubi  
--

.. Check that output from the previous command shows that the mirror registry is already populated with MicroShift release images (`openshift-release-dev/ocp-v4.0-art-dev`) and LVM Storage operator images (`lvms4/lvms-rhel9-operator`).

2. Configure the _development machine_ to use the mirror registry, so it can build bootc container images without internet access.

.. Configure the container runtime to get MicroShift release images from the mirror registry.
+
NOTE: The registry configuration file is the same one you already used to configure MicroShift in a xref:ch2-package:s2-install-lab[previous lab].
+
[source,subs="verbatim,quotes"]
--
$ *wget -q https://raw.githubusercontent.com/RedHatQuickCourses/rhde-build-samples/refs/heads/main/microshift/999-microshift-mirror.conf*
$ *sudo cp 999-microshift-mirror.conf /etc/containers/registries.conf.d*
--

.. Disable signature verification on container images required by MicroShift by downloading a https://github.com/RedHatQuickCourses/rhde-build-samples/blob/main/microshift/containers-policy.json.nosigs[container image policy file] from the course samples git repository.
+
[source,subs="verbatim,quotes"]
--
$ *wget -q https://raw.githubusercontent.com/RedHatQuickCourses/rhde-build-samples/refs/heads/main/microshift/containers-policy.json.nosigs*
$ *sudo cp containers-policy.json.nosigs /etc/containers/policy.json*
--

3. Download and inspect a containerfile for a preconfigured MicroShift instance. That container file requires the files downloaded during the previous step, and a few more files you will download right now.

.. Download the https://raw.githubusercontent.com/RedHatQuickCourses/rhde-build-samples/refs/heads/main/microshift/Containerfile-bootc[sample containerfile] from the course samples git repository. It is a long Containerfile but, assuming that you performed all activities from the the xref:ch2-package[previous chapter] of this course, there should be no surprises.
+
[source,subs="verbatim,quotes"]
--
$ *wget -q https://raw.githubusercontent.com/RedHatQuickCourses/rhde-build-samples/refs/heads/main/microshift/Containerfile-bootc*
--

.. Review the `Containerfile-bootc` file and make sure you understand its instructions:
+
NOTE: The code snippets here help you locate the relevant sections in the Containerfile, but they do not list the entirety of most sections. Follow along with a text editor and navigate through the blueprint file.

... Use the base RHEL 9 bootc container as the base image.
+
[source,subs="verbatim"]
--
include::1@samples:microshift:example$Containerfile-bootc[lines=1]
...
--

... Configure DNF repositories
+
[source,subs="verbatim"]
--
...
include::1@samples:microshift:example$Containerfile-bootc[lines=3]
...
--

... Install the MicroShift packages and dependencies. You need the optional `microshift-release-info` package because it provides the list of container images to embed in the bootc container image, later in this containerfile.
+
[source,subs="verbatim"]
--
...
include::1@samples:microshift:example$Containerfile-bootc[lines=5..7]
...
--

... Enables the Kubernetes pod and service networks on the Linux firewall, and expose the Kubernetes API endpoint and SSH port.
+
[source,subs="verbatim"]
--
...
include::1@samples:microshift:example$Containerfile-bootc[lines=10..13]
...
--

... Enable a first boot service, which sets file permissions required by OVN.
+
[source,subs="verbatim"]
--
...
include::1@samples:microshift:example$Containerfile-bootc[lines=17..28]
...
--

... Add a registry configuration which redirects MicroShift container images to the mirror registry.
+
[source,subs="verbatim"]
--
...
include::1@samples:microshift:example$Containerfile-bootc[lines=31]
...
--

... Add an image policy which disables signature validation.
+
[source,subs="verbatim"]
--
...
include::1@samples:microshift:example$Containerfile-bootc[lines=32]
...
--

... Add a CA certificate for the mirror registry. Remember that you download that CA file in the xref:ch1-microshift:s3-air-gapped-lab.adoc[first chapter]
+
[source,subs="verbatim"]
--
...
include::1@samples:microshift:example$Containerfile-bootc[lines=33..34]
...
--

... Embed the MicroShift release container images in the system image.
+
[source,subs="verbatim"]
--
...
include::1@samples:microshift:example$Containerfile-bootc[lines=40..52]
...
--

... Embed a script which copies the autogenerated kubeconfig files to the `core` user home directory. [ PENDING, DO ON KICKSTART? OR IN THE CONTAINERFILE? ]
+
[source,subs="verbatim"]
--
...
include::1@samples:microshift:example$Containerfile-bootc[lines=75]
...
--
+
NOTE: The script starts before MicroShift is fully initialized so it was coded to wait until MicroShift autogenerates the kubeconfig files.

.. Download DNF repository configuration files that refer to the _package server machine_.
+
[source,subs="verbatim,quotes"]
--
$ *mkdir yum.d*
$ *wget -qP yum.d https://raw.githubusercontent.com/RedHatQuickCourses/rhde-build-samples/refs/heads/main/microshift/yum.d/rhel-9.5-for-x86_64-baseos-rpms.repo*
$ *wget -qP yum.d https://raw.githubusercontent.com/RedHatQuickCourses/rhde-build-samples/refs/heads/main/microshift/yum.d/rhel-9.5-for-x86_64-appstream-rpms.repo*
$ *wget -qP yum.d https://raw.githubusercontent.com/RedHatQuickCourses/rhde-build-samples/refs/heads/main/microshift/yum.d/fast-datapath-for-rhel-9-x86_64-rpms.repo*
$ *wget -qP yum.d https://raw.githubusercontent.com/RedHatQuickCourses/rhde-build-samples/refs/heads/main/microshift/yum.d/rhocp-4.17-for-rhel-9-x86_64-rpms.repo*
--

.. Embed a test application container image in the bootc container image [ TBD ]

4. Download and inspect a blueprint for a customized installation ISO.

.. Download the https://raw.githubusercontent.com/RedHatQuickCourses/rhde-build-samples/refs/heads/main/microshift/config.toml[sample installer blueprint] from the course samples git repository. It basically contains a customized kickstart file.
+
[source,subs="verbatim,quotes"]
--
$ *wget -q https://raw.githubusercontent.com/RedHatQuickCourses/rhde-build-samples/refs/heads/main/microshift/config.toml*
--

.. Review the blueprint and make sure you understand it's kickstart instructions.
+
NOTE: The code snippets here help you locate the relevant sections in the kickstart file, but they do not list the entirety of the blueprint file. Follow along with a text editor and navigate through the kickstart file.

... Set a text-mode installation and preconfigure language and keyboard, so Anaconda can proceed unattended, and reboot at the end of the installation.
+
[source,subs="verbatim"]
--
...
include::1@samples:microshift:example$config.toml[lines=5..10]
...
--

... Partition the root disk with LVM, but taking only 10G for the root partition, in order to leave empty space in the `rhel` volume group for use by MicroShift's LVM Storage operator.
+
[source,subs="verbatim"]
--
...
include::1@samples:microshift:example$config.toml[lines=13..19]
...
--

... In a post install script,  create an initial user with a known password, unlimited sudo, and SSH key.
+
[source,subs="verbatim"]
--
...
include::1@samples:microshift:example$config.toml[lines=26..31]
...
--
+
NOTE: Production systems would NOT enable password login. We left it here as a convenience for the learner, so you can log in at the VM console for troubleshooting.

... Also in the post install script, add a pull secret for the mirror registry.
+
[source,subs="verbatim"]
--
...
include::1@samples:microshift:example$config.toml[lines=34..37]
...
--

... End the post install script by setting the hostname to `ushift` where the letter "u" stands for the Greek letter "micro", just for convenience.
+
[source,subs="verbatim"]
--
...
include::1@samples:microshift:example$config.toml[lines=40..41]
...
--

.. Create an SSH key for use with your edge devices.
+
[source,subs="verbatim,quotes"]
--
$ *ssh-keygen -N '' -f edge-key -C 'initial key for edge devices'*
Generating public/private rsa key pair.
...
--
+
NOTE: If you get an error, because you already have an `edge-key` generated from previous Red Hat Device Edge courses, just ignore the error and continue with the next step.

.. Embed your new SSH key in the blueprint.
+
[source,subs="verbatim,quotes"]
--
$ *SSH_PUB_KEY=$( cat edge-key.pub )*
$ *sed -i "s|REPLACE_WITH_SSH_PUB_KEY|$SSH_PUB_KEY|" config.toml*
--

.. Embed your pull secret in the blueprint.
+
[source,subs="verbatim,quotes"]
--
$ *PULL_SECRET=$( cat mirror-pull-secret )*
$ *sed -i "s|REPLACE_WITH_PULL_SECRET|$PULL_SECRET|" config.toml*
--

5. Build a bootc container image and embed it into an installation ISO.

.. Build a bootc container image.
+
[source,subs="verbatim,quotes"]
--
$ *podman build -f Containerfile-microshift -t rhde/microshift-bootc:4.17*
GRAB OUTPUT
--

.. Copy your bootc container image to the mirror registry.
+
[source,subs="verbatim,quotes,attributes"]
--
$ *skopeo copy containers-storage:localhost/rhde/microshift-bootc:4.17 docker://servera.lab.example.com:8443/rhde/microshift-bootc:4.17*
GRAB OUTPUT
--

.. Pull your bootc container image to the system container storage, so it can be read by bootc image builder.
+
[source,subs="verbatim,quotes"]
--
$ *sudo podman pull servera.lab.example.com:8443/rhde/microshift-bootc:4.17*
GRAB OUTPUT
--

.. Create an installable ISO containing your bootc container image and your custom kickstart file.
+
[source,subs="verbatim,quotes"]
--
$ *mkdir output*
$ *sudo podman run --rm -it --privileged --pull=newer \
    --security-opt label=type:unconfined_t \
    -v /var/lib/containers/storage:/var/lib/containers/storage \
    -v $(pwd)/config.toml:/config.toml \
    -v $(pwd)/output:/output \
    servera.lab.example.com:8443/rhel9/bootc-image-builder:9.5 \
    --type iso --local --config /config.toml \
    servera.lab.example.com:8443/rhde/microshift-bootc:4.17*
GRAB OUTPUT
--

.. Copy the installable ISO from the bootc image builder temporary output directory to a more permanent localtion, and give it an easily identifiable name. That file would be distributed to personel responsible for installing actual edge devices. 
+
[source,subs="verbatim,quotes"]
--
$ *cp output/bootiso/install.iso rhel9-microshift-bootc.iso*
--

6. On your _web server machine_, stop the mirror registry for Red Hat OpenShift, so you can prove that your installation disk can actually work in disconnected edge sites.
+
[source,subs="verbatim,quotes"]
--
$ *sudo systemctl stop quay-app quay-pod quay-redis*
$ *sudo systemctl is-active quay-app quay-pod quay-redis*
failed
inactive
inactive
--
+
NOTE: The `failed` state is expected for the `quay-app` service.

7. On your _development machine_, create a KVM virtual machine to test your edge installer image.

.. Set a shell variable with the disk label of your installer image, by copy-and-paste from the output of the `iso-info` command.
+
[source,subs="verbatim,quotes"]
--
$ *iso-info rhel9-microshift-bootc.iso*
...
Volume      : RHEL-9-5-0-BaseOS-x86_64
No Joliet extensions
$ *LABEL=RHEL-9-5-0-BaseOS-x86_64*
--

.. Create a KVM virtual machine from your installer image. The installation should proceed unattended until you get a login prompt. 
+
You could use different `virt-install` commands or the Cockpit web UI. The use of `--location` and `--extra-arg` in the following command enables the VM to run with a serial console, so you don't need to leave your shell and don't need to open a graphical console for your _edge machine_. [ CAN I USE A RELATIVE PATH WITH --location ? ]
+
[source,subs="verbatim,quotes"]
--
$ *virt-install --name edge-microshift-1 --os-variant rhel9.5 \
--memory 4096 --vcpus 2 --disk size=20 --graphics=none --network bridge=virbr0 \
--location /home/student/rhel9-microshift-bootc.iso \
--extra-arg inst.ks=hd:LABEL=$LABEL:/rhel9-microshift-installer.ks \
--extra-arg console=ttyS0 -v*
...
ushift login:
--
+
NOTE: You may need to press kbd:[Enter] to see the login prompt, after the VM stops displaying console messages.

.. Detach from the VM console, by pressing kbd:[Ctrl+\]], and start an SSH session to your _edge machine_.
+
[source,subs="verbatim,quotes"]
--
$ *ssh -i edge-key core@ushift*
--

8. On your _edge machine_, verify that MicroShift is fully initialized.

.. Check that MicroShift is healthy and all its pods are ready and running. Beware it may take a while for MicroShift to finish starting all its pods. [ ADD THE FIRST BOOT UNIT TO CREATE local-admin ]
+
[source,subs="verbatim,quotes"]
--
$ *export KUBECONFIG=~/local-admin*
$ *oc get node*
NAME     STATUS   ROLES                         AGE   VERSION
ushift   Ready    control-plane,master,worker   10m   v1.30.5
$ *oc get pod -A*
NAMESPACE                  NAME                                       READY   STATUS    RESTARTS   AGE
kube-system                csi-snapshot-controller-69ddff88c8-6g4wr   1/1     Running   0          4m20s
kube-system                csi-snapshot-webhook-74dc497864-xgjzz      1/1     Running   0          4m24s
openshift-dns              dns-default-tj2wf                          2/2     Running   0          4m5s
openshift-dns              node-resolver-lfg6k                        1/1     Running   0          4m21s
openshift-ingress          router-default-575b4fc7-cnnsc              1/1     Running   0          4m19s
openshift-ovn-kubernetes   ovnkube-master-xc84v                       4/4     Running   0          4m21s
openshift-ovn-kubernetes   ovnkube-node-mgsz2                         1/1     Running   0          4m21s
openshift-service-ca       service-ca-9db855698-pwbfg                 1/1     Running   0          4m19s
openshift-storage          lvms-operator-7f544467bc-94227             1/1     Running   0          4m22s
openshift-storage          vg-manager-5n494                           1/1     Running   0          3m55s
--
+
NOTE: If you are too quick, you may get a `NotReady` state from `oc get node`, or a "no resources found" error from `oc get pod`. If any of this happens, just wait a few seconds and try again.

.. As an additional check, create a test pod from the sample application image we included in the bootc container image. [ NOT YET ]
+
[source,subs="verbatim,quotes"]
--
$ *oc run shell -it --restart Never --image-pull-policy IfNotPresent --image servera.lab.example.com:8443/ubi9/ubi -- rpm -q redhat-release*
redhat-release-9.5-0.6.el9.x86_64
$ *oc delete pod shell*
pod "shell" deleted
--
+
IMPORTANT: If you create a pod with the default image pull policy of `Always` it will fail because we stopped the mirror registry.

You succeed in provisioning an edge device, from an installable ISO, in an air-gapped environment: you only need the installation media to fully provision a ready-to-use RHEL image mode system running a MicroShift instance.


== What's Next

This was the final activity of this course. If you wish, you can create service accounts and kubeconfig files for developer access using the same steps from ch2-package:s3-access-lab.adoc[previous labs] already demonstrated on RHEL package mode.

