:time_estimate: 9

= Lab: Prepare a Disconnected Environment for MicroShift

_Estimated reading time: *{time_estimate} minutes*._

Objective::

Populate a test environment with RPM packages and container images for air-gaped deployment of MicroShift.

== Before you Begin

You need a few machines to perform the hands-on activities in this course.

* A _development machine_ with RHEL and unrestricted `sudo`, where you will create test VMs using Libvirt, and also run the OpenShift client to access your MicroShift instances in other machines.

* A _test machine_ with RHEL and unrestricted `sudo`, where you will install MicroShift on RHEL package mode.

* A _package server machine_ already configured to serve DNF repositories for RHEL, Fast Datapath for RHEL, and Red Hat OpenShift Container Platform.

* A _web server machine_ with RHEL and unrestricted `sudo`, to share files such as public keys.

* A _mirror registry machine_ with RHEL and unrestricted `sudo`, to host a https://www.redhat.com/en/blog/introducing-mirror-registry-for-red-hat-openshift[mirror registry for Red Hat OpenShift^].

These instructions were tested on RHEL 9.5 but should work with minimal or no change on newer and older RHEL 9.x releases.

If you are using the course environment, you will log in to the `workstation` VM as the user `student` with password `student`.
The `workstation` VM is your _development machine_.
You will start SSH sessions from the `workstation` VM to the `servera` VM, which is your _web server machine_ and also your _mirror registry machine_, using the same user.

IMPORTANT: Be sure you execute each step on the correct machine.
If a step is not explicit about the machine it should be performed, it is using the same machine as its previous step.

In the course environment, the `classroom` VM, with the `materials` alias, is your _package server machine_ but you are _not_ expected to start SSH sessions nor perform any activity on it.

NOTE: It should be possible to perform all activities in this course using a https://developers.redhat.com/products/rhel/download[free Red Hat Developers free subscrition^], which gives you access to installation media, RPM packages, and container images for RHEL and Red Hat OpenShift.
If you ignore the requirements for air-gaped installation of MicroShift, you could use a single RHEL VM and adapt the steps to your own environment.

== Instructions

include::rhde-microshift:ch1-microshift:partial$s3-air-gapped-lab-registry.adoc[]

5. Populate the mirror registry with container images for RHEL image mode.

.. Download the bootc images from RHEL.
+
[source,subs="verbatim,quotes"]
--
$ *wget -q http://content.example.com/rhde/oci/bootc-containers.tar.gz*
$ *tar xzf bootc-containers.tar.gz*
$ *ls bootc-containers*
rhel9
$ *ls bootc-containers/rhel9/*
bootc-image-builder:9.5  rhel-bootc:9.5
--

.. Download the bootc images upload script.
It is very similar to the application images upload script.

+
[source,subs="verbatim,quotes"]
--
$ *wget -q https://raw.githubusercontent.com/RedHatQuickCourses/rhde-build-samples/refs/heads/main/sh/upload-bootc.sh*
--

.. Run the application images upload script.
Review carefully that its output does not indicate any errors.

+
[source,subs="verbatim,quotes"]
--
$ *sh upload-bootc.sh*
--

.. You can check that the upload process worked by listing all images in the mirror registry.
+
[source,subs="verbatim,quotes"]
--
$ *podman search servera.lab.example.com:8443/*
NAME                                                                 DESCRIPTION
servera.lab.example.com:8443/lvms4/lvms-rhel9-operator
servera.lab.example.com:8443/openshift-release-dev/ocp-v4.0-art-dev
servera.lab.example.com:8443/flozanorht/php-ubi
servera.lab.example.com:8443/rhel9/mysql-80
servera.lab.example.com:8443/ubi9/ubi
servera.lab.example.com:8443/rhel9/rhel-bootc
servera.lab.example.com:8443/rhel9/bootc-image-builder
--

include::rhde-microshift:ch1-microshift:partial$s3-air-gapped-lab-dnf.adoc[]

You now have your _mirror registry machine_ and your _package server machine_ ready to support the air-gapped deployment of MicroShift in both package and image modes of RHEL.

== What's Next

The next chapter features a series of hands-on activities that deploy MicroShift on a RHEL VM and configure unprivileged developer-level access to it.

